### ISSUE TITLE
最終課題挙動確認

### ISSUE THREAD

**Issue by david-masa** [david-masa/freemarket_sample_71a#61]
■ URL
IPアドレス：http://18.181.155.100/
Github（最終課題のリポジトリ）：https://github.com/david-masa/freemarket_sample_71a

■ Basic認証
ID：admin
Pass：2222

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer_user@gmail.com
パスワード：buyer_user

◯ 購入用カード情報
番号：4242424242424242
期限：12/20
セキュリティカード：123

◯ 出品者用
メールアドレス：seller_user1@gmail.com
パスワード：seller_user

**Comment by naokihayasan127** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
